name: fullstack_template

# REMEMBER TO CHANGE THE NAME AND POSTGRES DB NAME TO SATISFY YOUR OWN PROJECT

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fullstack_template
